# Generated by Django 5.0.10 on 2024-12-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('cd_lingua', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2, primary_key=True, serialize=False)),
                ('nome_lingua', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_lingua', max_length=50, null=True)),
            ],
            options={
                'db_table': 'lingua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_mesorregiao', models.SmallIntegerField()),
                ('nome_municipio', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_municipio', max_length=50)),
                ('numero_latitude', models.FloatField(blank=True, db_column='nr_latitude', null=True)),
                ('numero_longitude', models.FloatField(blank=True, db_column='nr_longitude', null=True)),
                ('id_municipio_ibge', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('cd_pais', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('nome_pais', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_pais', max_length=100)),
                ('cd_pais_ibge', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'País',
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('tipo_veiculo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tp_veiculo', max_length=3, primary_key=True, serialize=False)),
                ('descricao_tipo_veiculo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ds_tipo_veiculo', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de veículos',
                'db_table': 'tipo_veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('cd_uf', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='sg_uf', max_length=2, primary_key=True, serialize=False)),
                ('nome_uf', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_uf', max_length=50)),
                ('nome_regiao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_regiao', max_length=50)),
                ('cd_uf_ibge', models.SmallIntegerField(blank=True, null=True)),
                ('cd_pais', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('id_capital', models.SmallIntegerField(blank=True, null=True)),
                ('numero_gmt', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nr_gmt', max_length=50, null=True)),
            ],
            options={
                'db_table': 'uf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculosistemas',
            fields=[
                ('cd_veiculo', models.AutoField(db_column='CodVei', primary_key=True, serialize=False)),
                ('codsys', models.IntegerField(blank=True, db_column='CodSys', null=True)),
                ('nome_veiculo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NmoVei', max_length=510)),
                ('prioridade_veiculo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PriVei', max_length=2, null=True)),
                ('veiculo_nacional', models.BooleanField(blank=True, db_column='VeiNacional', null=True)),
                ('ordem_veiculo', models.IntegerField(blank=True, db_column='VeiOrdem', null=True)),
                ('codtipovei', models.IntegerField(blank=True, db_column='CodTipoVei', null=True)),
                ('situacao_veiculo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='st_veiculo', max_length=1, null=True)),
                ('endereco_site_veiculo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='end_veiculo', max_length=500, null=True)),
                ('nome_identificador_url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_identificador_url', max_length=100, null=True)),
                ('data_ultima_noticia', models.DateTimeField(blank=True, db_column='dt_ultima_noticia', null=True)),
                ('cd_usuario_web', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='cd_usuario_web', max_length=60, null=True)),
                ('cd_senha_web', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='cd_senha_web', max_length=60, null=True)),
                ('valor_publicitario_cm', models.DecimalField(blank=True, db_column='vl_publicitario_cm', decimal_places=4, max_digits=19, null=True)),
                ('cd_usuario_flip', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='cd_usuario_flip', max_length=60, null=True)),
                ('cd_senha_flip', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='cd_senha_flip', max_length=60, null=True)),
                ('nome_referencia', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_referencia', max_length=500, null=True)),
                ('endereco_flip', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='end_flip', max_length=500, null=True)),
                ('nome_url_stream', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_url_stream', max_length=4000, null=True)),
                ('in_domingo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='in_domingo', max_length=1, null=True)),
                ('in_segunda', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='in_segunda', max_length=1, null=True)),
                ('in_terca', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='in_terca', max_length=1, null=True)),
                ('in_quarta', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='in_quarta', max_length=1, null=True)),
                ('in_quinta', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='in_quinta', max_length=1, null=True)),
                ('in_sexta', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='in_sexta', max_length=1, null=True)),
                ('in_sabado', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='in_sabado', max_length=1, null=True)),
                ('situacao_url_stream', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='st_url_stream', max_length=3, null=True)),
                ('quantidade_publico', models.IntegerField(blank=True, db_column='qt_publico', null=True)),
                ('numero_telefone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nr_telefone', max_length=30, null=True)),
                ('nome_endereco', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='no_endereco', max_length=300, null=True)),
                ('data_atualizacao', models.DateField(blank=True, db_column='dt_atualizacao', null=True)),
                ('tolerancia_sem_noticia', models.IntegerField(blank=True, db_column='tolerancia_sem_noticia', null=True)),
                ('quantidade_min_noticia', models.IntegerField(blank=True, db_column='qt_min_noticia', null=True)),
                ('periodo_publicacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='periodo_publicacao', max_length=1, null=True)),
                ('texto_comando_encoder', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tt_comando_encoder', max_length=2000, null=True)),
                ('cm_altura', models.DecimalField(blank=True, db_column='cm_altura', decimal_places=2, max_digits=6, null=True)),
                ('cm_largura', models.DecimalField(blank=True, db_column='cm_largura', decimal_places=2, max_digits=6, null=True)),
                ('json_lst_etiqueta', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='json_lst_etiqueta', null=True)),
                ('in_extrair_texto_ocr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='in_extrair_texto_ocr', max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Veículos',
                'db_table': 'VeiculoSistemas',
                'managed': False,
            },
        ),
    ]
