# Generated by Django 5.0.10 on 2024-12-23 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpContrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('cd_identificacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP850_CI_AI', max_length=20, null=True)),
                ('descricao_contrato', models.CharField(db_collation='SQL_Latin1_General_CP850_CI_AI', max_length=1000)),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('tipo_prorrogacao', models.CharField(db_collation='SQL_Latin1_General_CP850_CI_AI', max_length=3)),
                ('descricao_objeto', models.TextField(db_collation='SQL_Latin1_General_CP850_CI_AI')),
                ('informacao_adicional', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP850_CI_AI', null=True)),
                ('valor_contrato', models.DecimalField(decimal_places=4, max_digits=19)),
                ('dia_emissao_nota_fiscal', models.IntegerField()),
                ('status_contrato', models.CharField(db_collation='SQL_Latin1_General_CP850_CI_AI', max_length=1)),
                ('in_contrato_assinado', models.BooleanField()),
                ('tipo_cobranca', models.CharField(db_collation='SQL_Latin1_General_CP850_CI_AI', max_length=3)),
                ('data_cadastro', models.DateTimeField()),
                ('dia_do_pagamento', models.IntegerField()),
                ('dia_aviso_fim_vigencia', models.IntegerField(blank=True, null=True)),
                ('forma_envio_nf', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP850_CI_AI', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'db_table': 'erp_contrato',
                'ordering': ['status_contrato'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErpProduto',
            fields=[
                ('cd_produto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP850_CI_AI', max_length=100)),
                ('situacao_produto', models.BooleanField(default=True)),
                ('cd_produto_principal', models.ForeignKey(blank=True, db_column='cd_produto_principal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_produtos', to='contratos.erpproduto')),
                ('veiculos', models.ManyToManyField(related_name='produtos', to='veiculos.veiculosistemas')),
            ],
            options={
                'verbose_name': 'Produto',
                'db_table': 'erp_produto',
                'ordering': ['cd_produto'],
                'managed': True,
            },
        ),
    ]
